#!/usr/bin/env bash
# Sync the registry-generated .mcp.json to Claude Code, Cursor, and VS Code.
# The source of truth is mcp/registry.json — .mcp.json is regenerated by install-mcps.sh.
# Idempotent — safe to run multiple times.
set -euo pipefail

FACTORY_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MCP_SOURCE="${FACTORY_ROOT}/.mcp.json"

echo "── Syncing MCP config to all editors ───────────────"

# Claude Code (also regenerates .mcp.json from mcp/registry.json)
bash "${FACTORY_ROOT}/scripts/install-mcps.sh" && echo "[ok]  Claude Code synced" || echo "[warn] Claude Code sync failed"

# Cursor (~/.cursor/mcp.json or %APPDATA%\Cursor\mcp.json)
if [[ "$OSTYPE" == "darwin"* ]]; then
  CURSOR_DIR="${HOME}/.cursor"
elif [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
  CURSOR_DIR="${APPDATA}/Cursor"
else
  CURSOR_DIR="${HOME}/.config/Cursor"
fi

if [[ -d "$CURSOR_DIR" ]]; then
  cp "$MCP_SOURCE" "${CURSOR_DIR}/mcp.json"
  echo "[ok]  Cursor MCP config written to: ${CURSOR_DIR}/mcp.json"
else
  echo "[info] Cursor not detected — skipping"
fi

# VS Code workspace settings (.vscode/mcp.json uses {servers: ...} shape)
VSCODE_DIR="${FACTORY_ROOT}/.vscode"
mkdir -p "$VSCODE_DIR"
if command -v jq &>/dev/null; then
  jq '{servers: .mcpServers}' "$MCP_SOURCE" > "${VSCODE_DIR}/mcp.json"
  echo "[ok]  VS Code MCP config written to: ${VSCODE_DIR}/mcp.json"
else
  echo "[warn] jq not available — VS Code MCP config not written"
fi

echo ""
echo "[ok]  Sync complete. Restart editors to load updated MCP servers."
